### ISSUE TITLE
CCE Image EulerOS 2.9 is missing and Euler 2.5 image not available

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/cloud-container-engine#21]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/nodes/overview.rst

There is no information about EulerOS 2.9 images.
The image information Euler 2.5 is not relevant because this image is not available in OTC Console.

Can you please update documentation?

Thank you
Robert

**Comment by oeotvos** [comment]
Hi Robert. Thank you for your remark. The issue will be resolved soon.
Regards, 
Oliver
(int#CONT-1274)

**Comment by oeotvos** [comment]
Thank you for the input, the table was updated.
https://docs.otc.t-systems.com/cloud-container-engine/umn/nodes/node_overview/container_engine.html
