### ISSUE TITLE
OS Patch Notes for Cluster Nodes not up2date

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/cloud-container-engine#26]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/product_bulletin/os_patch_notes_for_cluster_nodes.rst

Would you please update the documentation to what is available for customer?

EulerOS release 2.0 (SP2) | 3.10.0-327.62.59.83.h128.x86_64 ---> not available anymore
EulerOS release 2.0 (SP5) | 3.10.0-862.14.1.5.h591.eulerosv2r7.x86_64 ---> pls check / docu not up2date
EulerOS release 2.0 (SP9) | 4.18.0-147.5.1.6.h541.eulerosv2r9.x86_64 ---> pls check / docu not up2date
CentOS Linux release 7.7 | 3.10.0-1062.18.1.el7.x86_64 ---> pls check / docu not up2date

**Comment by oeotvos** [comment]
Hi Robert, thank you. The versions will be corrected together with missing EulerOS asap.

**Comment by oeotvos** [comment]
The documentation was updated, thank you.
https://docs.otc.t-systems.com/cloud-container-engine/umn/product_bulletin/os_patch_notes_for_cluster_nodes.html
