### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by EHJ-52n** [opentelekomcloud-docs/cloud-container-engine#47]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/instruction.rst

The link [Creating a CCE Cluster](https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0028.html) is not working. The linked page is not found!

**Comment by oeotvos** [comment]
Thank you for your input. The correction is on the way.
(https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-container-engine/pulls/59/files)

**Comment by EHJ-52n** [comment]
You're welcome! 

Your link is not working (anymore?)!?
