### ISSUE TITLE
Creating a Node

### ISSUE THREAD

**Issue by zkovacsd** [opentelekomcloud-docs/cloud-container-engine#51]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/nodes/creating_a_node.rst

Under "Storage Settings --> Table 2 Configuration parameters"

The explanation for "System Disk Encryption" starts with "Encryption: Data disk encryption safeguards your data", but I think it should start with  "System disk encryption safeguards your data"

**Comment by oeotvos** [comment]
Thank you for your input. The solution is on the way.
https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-container-engine/pulls/59/files#issuecomment-40862
