### ISSUE TITLE
CCE Turbo Clusters and CCE Clusters

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/cloud-container-engine#52]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/clusters/cluster_overview/cce_turbo_clusters_and_cce_clusters.rst

Please remove "QingTian" as naming of the architecture.

**Comment by oeotvos** [comment]
It's the name of Huawei architecture we use so we can't remove it. Description of the technology is publicly available.
