### ISSUE TITLE
Creating a CCE Cluster did not work and got "Page not found" error

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/cloud-container-engine#53]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/instruction.rst

[Creating a CCE Cluster](https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0028.html) did not work and got "Page not found" error

**Comment by oeotvos** [comment]
Thank you for your input. The solution is on the way.
(https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-container-engine/pulls/59/files)

**Comment by oeotvos** [comment]
The link has been updated. Thanks.
