### ISSUE TITLE
CCE Turbo Clusters and CCE Clusters

### ISSUE THREAD

**Issue by EHJ-52n** [opentelekomcloud-docs/cloud-container-engine#58]
Issue on page: "CCE Turbo Clusters and CCE Clusters"

- Source: https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/clusters/cluster_overview/cce_turbo_clusters_and_cce_clusters.rst

- Rendered: https://docs.otc.t-systems.com/cloud-container-engine/umn/clusters/cluster_overview/cce_turbo_clusters_and_cce_clusters.html

There is a link or statement missing the pricing difference. If there are none, please add an according statement.

**Comment by oeotvos** [comment]
The CCE Turbo has not been released as General Available version yet. The official GA version will be announced soon together with billing details. Pricing information is not part of the UMN, but Price Calculator (where CCE Turbo info may be added). At the moment, the price of the CCE Turbo clusters equals to CCE clusters.
Thank you for your remark based on which we will improve this pricing information.

**Comment by oeotvos** [comment]
[OTCPR-14805]

**Comment by oeotvos** [comment]
As mentioned already, no pricing info has place in the UMN, but the Price calculator - already updated with the turbo.
Thanks for notice.
