### ISSUE TITLE
Deleting an Add-on Instance missing arguments documentation

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud-docs/cloud-container-engine#66]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/api-ref/source/apis/add-on_management/deleting_an_add-on_instance.rst

**Comment by oeotvos** [comment]
Unfortunately I can not observe the issue so closing the ticket, please reopen and specify when needed. Thank you.
