### ISSUE TITLE
Creating a LoadBalancer Service - incorrect band_width_chargemode

### ISSUE THREAD

**Issue by brieseme** [opentelekomcloud-docs/cloud-container-engine#78]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/network/service/loadbalancer/creating_a_loadbalancer_service.rst

Regarding the referring API doc (https://docs.otc.t-systems.com/elastic-load-balancing/api-ref/apis_v3/load_balancer/creating_a_load_balancer.html#createloadbalancer-request-createloadbalancerbandwidthoption), parameter "bandwidth_chargemode" has to be "traffic" instead of "bandwidth":

<img width="793" alt="image" src="https://github.com/opentelekomcloud-docs/cloud-container-engine/assets/42633813/2769a818-e1f3-48ac-91bf-c7bcd077f4fa">

**Comment by oeotvos** [comment]
Thank you for your findings. 
(Internal CONT-2625)

**Comment by oeotvos** [comment]
UMN fixed:
https://docs.otc.t-systems.com/cloud-container-engine/umn/network/service/loadbalancer/creating_a_loadbalancer_service.html#cce-10-0681
API will be updated soon.
