### ISSUE TITLE
Release Notes for CCE Cluster Versions

### ISSUE THREAD

**Issue by k11h-de** [opentelekomcloud-docs/cloud-container-engine#81]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-container-engine/blob/main/umn/source/clusters/cluster_overview/release_notes_for_cce_cluster_versions.rst

Release notes are missing for current patch version "v1.25.6-r4"

**Comment by oeotvos** [comment]
Thank you for the note. Yes, we will release the notes for all other minor versions soon. Together with the upgrade function.

**Comment by oeotvos** [comment]
The issue has been resolved, thank you for a hint.
https://docs.otc.t-systems.com/cloud-container-engine/umn/clusters/cluster_overview/release_notes_for_cce_cluster_versions.html
